# -*- coding: utf-8 -*-
"""Jamu PMPL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xnRrR1CHuq0RTNeeP2rFAisugtkBpla0

# Import Library
"""

import pandas as pd
import re
import string
import nltk
import joblib

from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.base import BaseEstimator, TransformerMixin
from imblearn.over_sampling import RandomOverSampler
from imblearn.pipeline import Pipeline

nltk.download('stopwords')

"""# Load Data"""

df = pd.read_csv("data jamu.csv")

df

print(df.isnull().sum())
df = df.dropna(subset=['KHASIAT'])
print("Jumlah data setelah drop:", len(df))

"""# Labeling"""

def labeling(text):
    text = str(text).lower()

    if any(k in text for k in [
        'stamina','tenaga','energi','lelah','capek','letih','lesu','loyo',
        'ejakulasi','perkasa','kejantanan','sperma','vitalitas','daya tahan',
        'kuat','kebugaran','fit','tidak mudah capek','menambah tenaga',
        'bab','buang air besar','nafsu makan','maag','asam lambung',
        'lemak','diet','kolesterol','berat badan','melangsingkan',
        'pelangsing','gemuk','kurus','metabolisme','pencernaan',
        'kembung','mual','perut','lambung','pegal','linu',
        'nyeri','rematik','encok','sendi','otot',
        'demam','flu','batuk','pilek',
        'diabetes','hipertensi','imun',
        'asma','ginjal','jantung','radang'
    ]):
        return 'stamina'

    elif any(k in text for k in [
        'keputihan','vagina','rahim','haid','menstruasi',
        'asi','kandungan','organ intim','hormonal'
    ]):
        return 'kesehatan_wanita'

    elif any(k in text for k in [
        'kulit','wajah','jerawat','komedo','cerah','halus',
        'glowing','keriput','flek','cantik',
        'gatal','alergi','jamur','eksim','panu',
        'bau badan','bau mulut','keringat'
    ]):
        return 'perawatan'

    else:
        return 'lainnya'

df['label'] = df['KHASIAT'].apply(labeling)

"""# Preprocessing"""

kamus = pd.read_excel('kamuskatabaku.xlsx')
kamus_dict = dict(zip(kamus['slang'], kamus['formal']))

class TextPreprocessor(BaseEstimator, TransformerMixin):
    def __init__(self):
        self.stop_words = set(stopwords.words('indonesian'))
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        return [self.clean_text(text) for text in X]
    def clean_text(self, text):
        text = str(text).lower()
        text = re.sub(r'http\S+|www\S+', '', text)
        text = re.sub(r'\d+', '', text)
        text = text.translate(str.maketrans('', '', string.punctuation))
        text = re.sub(r'\s+', ' ', text).strip()
        tokens = text.split()
        tokens = [kamus_dict.get(word, word) for word in tokens]
        tokens = [w for w in tokens if w not in self.stop_words]

        return " ".join(tokens)

"""# Split Data"""

X = df['KHASIAT']
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.1,
    random_state=42,
    stratify=y
)

"""# Modelling"""

pipeline = Pipeline([
    ('prep', TextPreprocessor()),
    ('tfidf', TfidfVectorizer()),
    ('ros', RandomOverSampler(random_state=42)),
    ('nb', MultinomialNB())
])

pipeline.fit(X_train, y_train)

"""# Evaluasi Model"""

y_pred = pipeline.predict(X_test)
print("\n=== HASIL EVALUASI ===")
print(classification_report(y_test, y_pred))

"""# Simpan Model"""

joblib.dump(pipeline, "model_pipeline.pkl")

print("\nModel berhasil disimpan sebagai model_pipeline.pkl")

"""# **Prediksi**"""

import pandas as pd
import joblib

model = joblib.load("model_pipeline.pkl")

kamus = pd.read_excel("kamuskatabaku.xlsx")

kamus_dict = dict(zip(kamus['slang'], kamus['formal']))

def correct_typo(text):
    tokens = text.lower().split()

    corrected = [
        kamus_dict.get(word, word)
        for word in tokens
    ]

    return " ".join(corrected)

text = "sakit prut uda beberapa hr dan nyri bdan"
fixed_text = correct_typo(text)

label = model.predict([fixed_text])[0]
prob  = model.predict_proba([fixed_text]).max()

print("Input Asli :", text)
print("Setelah Fix:", fixed_text)
print("Prediksi   :", label)
print("Confidence :", prob)